### Set endpoint
@pc-ip = {{pc_ip}}
@basic_auth = Basic {{username}} {{password}}
@contentType = application/json
@accept = application/json

### GET policies
# @name policies
curl --request -X GET \
    --url "https://{{pc-ip}}:8443/rest/v1.0/policies?pageSize=100&pageNumber=1" \
    --insecure \
    --header "Accept: {{accept}}" \
    --header "Content-Type: {{contentType}}" \
    --header "Authorization: {{basic_auth}}"

### Set a variable to GET a policy
@policy_uuid = {{policies.response.body.entities[2].uuid}}

### GET policy using uuid
# @name policy
curl --request GET \
    --url "https://{{pc-ip}}:8443/rest/v1.0/policies/{{policy_uuid}}" \
    --header "Accept: {{accept}}" \
    --header "Content-Type: {{contentType}}" \
    --header "Authorization: {{basic_auth}}"

### GET targets
# @name targets
curl --request -X GET \
    --url "https://{{pc-ip}}:8443/rest/v1.0/targets?pageSize=100&pageNumber=1&includeDatastores=false&forceSync=false" \
    --insecure \
    --header "Accept: {{accept}}" \
    --header "Content-Type: {{contentType}}" \
    --header "Authorization: {{basic_auth}}"

### Set a variable to GET a target
@target_uuid = {{targets.response.body.entities[0].uuid}}

### GET target using uuid
# @name target
curl --request GET \
    --url "https://{{pc-ip}}:8443/rest/v1.0/targets/{{target_uuid}}" \
    --header "Accept: {{accept}}" \
    --header "Content-Type: {{contentType}}" \
    --header "Authorization: {{basic_auth}}"

### GET vms
# @name vms
curl --request -X GET \
    --url "https://{{pc-ip}}:8443/rest/v1.0/vms?pageSize=100&pageNumber=1&forceSync=false" \
    --insecure \
    --header "Accept: {{accept}}" \
    --header "Content-Type: {{contentType}}" \
    --header "Authorization: {{basic_auth}}"

### Set a variable to GET a vm uuid
@vm_uuid = {{vms.response.body.entities[17].uuid}}

### Assign VM to policy
# @name vm_policy_assign
curl --request -X POST \
    --url "https://{{pc-ip}}:8443/rest/v1.0/policies/{{policy_uuid}}/assign" \
    --insecure \
    --header "Accept: {{accept}}" \
    --header "Content-Type: {{contentType}}" \
    --header "Authorization: {{basic_auth}}" \
    -d '{"vmUuidList": ["{{vm_uuid}}"]}'

### Backup VM using uuid
# @name backup
curl --request -X POST \
    --url "https://{{pc-ip}}:8443/rest/v1.0/vms/backup" \
    --insecure \
    --header "Accept: {{accept}}" \
    --header "Content-Type: {{contentType}}" \
    --header "Authorization: {{basic_auth}}" \
    -d '{
        "targetUuid": "{{target_uuid}}",
        "backupType": "FULL_BACKUP",
        "hypervisorUuid": null,
        "vmUuid": "{{vm_uuid}}"
        }'

### Backup VM using schedule
# @name schedule_backup
curl --request -X POST \
    --url "https://{{pc-ip}}:8443/rest/v1.0/schedules/backup" \
    --insecure \
    --header "Accept: {{accept}}" \
    --header "Content-Type: {{contentType}}" \
    --header "Authorization: {{basic_auth}}" \
    -d '{
        "uuidList": ["{{vm_uuid}}"]
        }'

### GET Jobs
# @name jobs
curl --request -X GET \
    --url "https://{{pc-ip}}:8443/rest/v1.0/jobs?pageSize=100&pageNumber=1" \
    --insecure \
    --header "Accept: {{accept}}" \
    --header "Content-Type: {{contentType}}" \
    --header "Authorization: {{basic_auth}}"

@job_uuid = {{jobs.response.body.entities[0].uuid}}

### GET Job Status
# @name backup_status
curl --request -X GET \
    --url "https://{{pc-ip}}:8443/rest/v1.0/jobs/{{job_uuid}}" \
    --insecure \
    --header "Accept: {{accept}}" \
    --header "Content-Type: {{contentType}}" \
    --header "Authorization: {{basic_auth}}"