@@{FETCH_CREDS}@@
PC_CREDS = fetch_cred("prism")
PC_PROVIDER_USERNAME = PC_CREDS.username
PC_PROVIDER_SECRET = PC_CREDS.secret

SELF_SERVICE_CREDS = fetch_cred("calm")
SELF_SERVICE_USERNAME = SELF_SERVICE_CREDS.username
SELF_SERVICE_SECRET = SELF_SERVICE_CREDS.secret

INFOBLOX_CREDS = fetch_cred("infoblox")
INFOBLOX_USERNAME = INFOBLOX_CREDS.username
INFOBLOX_SECRET = INFOBLOX_CREDS.secret

print("PC_PROVIDER_USERNAME={}".format(PC_PROVIDER_USERNAME))
print("PC_PROVIDER_SECRET,secret={}".format(PC_PROVIDER_SECRET))
print("SELF_SERVICE_USERNAME={}".format(SELF_SERVICE_USERNAME))
print("SELF_SERVICE_SECRET,secret={}".format(SELF_SERVICE_SECRET))
print("INFOBLOX_USERNAME={}".format(INFOBLOX_USERNAME))
print("INFOBLOX_SECRET,secret={}".format(INFOBLOX_SECRET))